branch-defaults:
  main:
    environment: null
    group_suffix: null
environment-defaults:
  alttext-django-env:
    branch: null
    repository: null
  django-env:
    branch: null
    repository: null
global:
  application_name: alttextproject
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: alttextadmin
  repository: null
  sc: git
  workspace_type: Application
